theme: jekyll-theme-minimal
title: Yaakov Bressler Personal Site
description: Welcome to my personal website! (This site is a stub for future work.)
logo_alt: Koala Time Logo
plugins:
  - jekyll-seo-tag
  - jekyll-menus
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-github-metadata

relative_links:
  enabled:     true
  collections: false

### Build settings ###
github:
  repository_url: https://github.com/ybressler/personal-website
  owner_url: https://github.com/ybressler
  is_project_page: False
  is_user_page: True

repository: personal-website
baseurl: ""

# SEO Stuff
url: https://new.yaakovbressler.com
twitter:
  username: yaakovbressler
  card: summary
