theme: jekyll-theme-minimal
title: Yaakov Bressler Personal Site
description: Welcome to my personal website! (This site is a stub for future work.)
url: https://new.yaakovbressler.com

relative_links:
  enabled:     true
  collections: false

kramdown:
    auto_ids: true

### Build settings ###
plugins:
  - jekyll-seo-tag
  - jekyll-menus
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-github-metadata

github:
  repository_url: https://github.com/ybressler/personal-website
  repository_name: YB Personal Site
  owner_url: https://github.com/ybressler
  is_project_page: False
  is_user_page: True

repository: ybressler/personal-website
baseurl: ""

# SEO Stuff
twitter:
  username: yaakovbressler
  card: summary

# User settings
username: Yaakov Bressler
user_description: Data Engineer

twitter_username: yaakovbressler
linkedin_username: yaakovbressler
github_username:  ybressler
medium_username: yaakovbressler
medium_url: https://yaakovbressler.medium.com/
email_form: https://google.com/
